# Generated by Django 5.2.5 on 2025-08-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="national_id",
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
