# Generated by Django 5.2.5 on 2025-08-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_profile_image_alter_profile_national_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="national_id",
            field=models.IntegerField(default=0),
        ),
    ]
