# Generated by Django 5.2.5 on 2025-09-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
