# Generated by Django 5.2.5 on 2025-09-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_pub_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="pub_date",
        ),
    ]
